version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-tech-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://et.tashonduras.com
      # Variables loaded from .env file
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow access to host services if needed
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true
    name: cloudflare_default
